package ntu.celt.eUreka2.modules.usage;

public enum UsageType {
	ANNOUNCEMENT
	,FORUM_THREAD, FORUM_THREAD_LIKE, FORUM_THREAD_YOU_LIKE
	, FORUM_THREAD_DISLIKE, FORUM_THREAD_YOU_DISLIKE 
	, FORUM_THREAD_REPLY, FORUM_THREAD_REPLY_LIKE, FORUM_THREAD_REPLY_YOU_LIKE
	, FORUM_THREAD_REPLY_DISLIKE, FORUM_THREAD_REPLY_YOU_DISLIKE
	, FORUM_REFLECTION
	,BLOG, BLOG_COMMENT, BLOG_REFLECTION
	,ELOG, ELOG_COMMENT, ELOG_REFLECTION
	,RESOURCE_FOLDER, RESOURCE_LINK, RESOURCE_FILE, RESOURCE_FILE_VERSION
	,SCHEDULING_MILESTONE, SCHEDULING_PHASE, SCHEDULING_TASK, SCHEDULING_ASSIGNED_TASK  
	
}
